// REGISTER CONSTANTS 
export const REGISTER_START="REGISTER_START";
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAIL="REGISTER_FAIL";

// LOADUSERDETAIL
export const LOAD_USER_DETAIL_START="LOAD_USER_DETAIL_START";
export const LOAD_USER_DETAIL_SUCCESS="LOAD_USER_DETAIL_SUCCESS";
export const LOAD_USER_DETAIL_FAIL="LOAD_USER_DETAIL_FAIL";

// LOGIN CONSTANTS 
export const LOGIN_START="LOGIN_START";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";

// LOGOUT 
export const LOGOUT_START="LOGOUT_START";
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const LOGOUT_FAIL="LOGOUT_FAIL";

// PROFILE DATA 
export const PROFILE_START="PROFILE_START";
export const PROFILE_SUCCESS="PROFILE_SUCCESS";
export const PROFILE_FAIL="PROFILE_FAIL";

// FOLLOWING
export const FOLLOWING_START="FOLLOWING_START";
export const FOLLOWING_SUCCESS="FOLLOWING_SUCCESS";
export const FOLLOWING_FAIL="FOLLOWING_FAIL";

// GETTING ALL POSTS 
export const GETTING_ALLPOST_START="GETTING_ALLPOST_START";
export const GETTING_ALLPOST_SUCCESS="GETTING_ALLPOST_SUCCESS";
export const GETTING_ALLPOST_FAIL="GETTING_ALLPOST_FAIL";


// LIKE AND DISLIKE POSTS 
export const LIKE_AND_DISLIKE_START="LIKE_AND_DISLIKE_START";
export const LIKE_AND_DISLIKE_SUCCESS="LIKE_AND_DISLIKE_SUCCESS";
export const LIKE_AND_DISLIKE_FAIL="LIKE_AND_DISLIKE_FAIL";

// SUGGESTION 
export const SUGGESTION_START="SUGGESTION_START";
export const SUGGESTION_SUCCESS="SUGGESTION_SUCCESS";
export const SUGGESTION_FAIL="SUGGESTION_FAIL";

// UPLOAD 
export const UPLOAD_START="UPLOAD_START";
export const UPLOAD_SUCCESS="UPLOAD_SUCCESS";
export const UPLOAD_FAIL="UPLOAD_FAIL";

// COMMENT 
export const COMMENT_START="COMMENT_START";
export const COMMENT_SUCCESS="COMMENT_SUCCESS";
export const COMMENT_FAIL="COMMENT_FAIL";

